// ── Document Type Metadata ─────────────────────────────────

export const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  blood_report:        'Blood Report',
  prescription:        'Prescription',
  xray:                'X-Ray',
  ct_mri:              'CT / MRI',
  discharge_summary:   'Discharge Summary',
  lab_report:          'Lab Report',
  vaccination_record:  'Vaccination Record',
  other:               'Other',
  'Lab Report':        'Lab Report',
  'Prescription':      'Prescription',
  'Imaging':           'Imaging',
  'Discharge Summary': 'Discharge Summary',
  'Vaccination':       'Vaccination',
  'Consultation':      'Consultation',
  'Other':             'Other',
};

export const DOCUMENT_TYPE_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  blood_report:       { bg: '#FFF0F0', text: '#8B2020', border: '#F5BFBF' },
  prescription:       { bg: '#FFF4EC', text: '#8B4A20', border: '#F5D4BA' },
  xray:               { bg: '#F0F4FF', text: '#204A8B', border: '#BAC8F5' },
  ct_mri:             { bg: '#F4F0FF', text: '#4A208B', border: '#C8BAF5' },
  discharge_summary:  { bg: '#F0FFF4', text: '#208B4A', border: '#BAF5C8' },
  lab_report:         { bg: '#FFFFF0', text: '#8B8B20', border: '#F5F5BA' },
  vaccination_record: { bg: '#F0FFF8', text: '#208B6B', border: '#BAF5E0' },
  other:              { bg: '#FAF7F2', text: '#7A6040', border: '#E8DDD0' },
  'Lab Report':       { bg: '#FFFFF0', text: '#8B8B20', border: '#F5F5BA' },
  'Prescription':     { bg: '#FFF4EC', text: '#8B4A20', border: '#F5D4BA' },
  'Imaging':          { bg: '#F0F4FF', text: '#204A8B', border: '#BAC8F5' },
  'Discharge Summary':{ bg: '#F0FFF4', text: '#208B4A', border: '#BAF5C8' },
  'Vaccination':      { bg: '#F0FFF8', text: '#208B6B', border: '#BAF5E0' },
  'Consultation':     { bg: '#FAF7F2', text: '#7A6040', border: '#E8DDD0' },
  'Other':            { bg: '#FAF7F2', text: '#7A6040', border: '#E8DDD0' },
};

// ── Language Labels ────────────────────────────────────────

export const LANGUAGE_LABELS = {
  en: 'English',
  hi: 'हिंदी',
  gu: 'ગુજરાતી',
} as const;

// ── Categories for sidebar ─────────────────────────────────

export const DOCUMENT_CATEGORIES: { type: string; label: string }[] = [
  { type: 'all',              label: 'All Records' },
  { type: 'blood_report',     label: 'Blood Reports' },
  { type: 'prescription',     label: 'Prescriptions' },
  { type: 'xray',             label: 'X-Rays' },
  { type: 'ct_mri',           label: 'CT / MRI' },
  { type: 'discharge_summary',label: 'Discharge Summaries' },
  { type: 'lab_report',       label: 'Lab Reports' },
  { type: 'vaccination_record',label: 'Vaccination Records' },
  { type: 'other',            label: 'Other' },
];

// ── Timeline event labels ──────────────────────────────────

export const TIMELINE_EVENT_LABELS = {
  record_added:      'Record Added',
  doctor_visit:      'Doctor Visit',
  prescription:      'Prescription',
  vaccination:       'Vaccination',
  lab_result:        'Lab Result',
  surgery:           'Surgery',
  hospitalization:   'Hospitalization',
};

// ── AI Disclaimer ─────────────────────────────────────────

export const AI_DISCLAIMER =
  'This explanation is generated by AI for informational purposes only. ' +
  'It is not a medical diagnosis, and should not replace the advice of a qualified ' +
  'healthcare professional. Always consult your doctor before making any health decisions.';
