import type { DB } from './store';
import { addDays, toISODate } from './schedule';

/**
 * Unified demo data for FamilyCare.
 * All modules (Dashboard, Family, Tree, Records, Medicines, Doctors, Vaccinations, Emergency)
 * share these exact IDs and family structure.
 */
export function seed(): DB {
  const today = toISODate(new Date());

  return {
    members: [
      {
        id: 'member-001',
        name: 'Tirth Patel',
        relation: 'Self',
        relationship: 'Self',
        dateOfBirth: '2002-11-14',
        gender: 'Male',
        bloodGroup: 'B+',
        avatarInitials: 'TP',
        avatarColor: '#B86F52',
        allergies: ['Penicillin'],
        conditions: [],
        emergencyContact: '+91 98765 43210',
        emergencyContactName: 'Rajesh Patel (Father)',
        notes: 'Primary account manager.',
        activeMedicineCount: 1,
        medicalRecordCount: 1,
      },
      {
        id: 'member-002',
        name: 'Meena Patel',
        relation: 'Mother',
        relationship: 'Mother',
        dateOfBirth: '1972-03-22',
        gender: 'Female',
        bloodGroup: 'A+',
        avatarInitials: 'MP',
        avatarColor: '#7C9274',
        allergies: ['Sulfa drugs', 'Dust mites'],
        conditions: ['Type 2 Diabetes', 'Hypertension'],
        emergencyContact: '+91 98765 43210',
        emergencyContactName: 'Rajesh Patel (Husband)',
        notes: 'Monitors blood glucose daily.',
        activeMedicineCount: 3,
        medicalRecordCount: 2,
      },
      {
        id: 'member-003',
        name: 'Rajesh Patel',
        relation: 'Father',
        relationship: 'Father',
        dateOfBirth: '1968-07-08',
        gender: 'Male',
        bloodGroup: 'B+',
        avatarInitials: 'RP',
        avatarColor: '#6B4636',
        allergies: [],
        conditions: ['Hypothyroidism', 'Mild Arthritis'],
        emergencyContact: '+91 98765 43210',
        emergencyContactName: 'Meena Patel (Wife)',
        notes: 'Takes morning thyroid medication.',
        activeMedicineCount: 2,
        medicalRecordCount: 1,
      },
      {
        id: 'member-004',
        name: 'Hirabhai Patel',
        relation: 'Grandfather',
        relationship: 'Grandfather',
        dateOfBirth: '1945-01-30',
        gender: 'Male',
        bloodGroup: 'O+',
        avatarInitials: 'HP',
        avatarColor: '#927565',
        allergies: ['Aspirin'],
        conditions: ['Type 2 Diabetes', 'Coronary Artery Disease', 'Cataracts'],
        emergencyContact: '+91 98765 43210',
        emergencyContactName: 'Rajesh Patel (Son)',
        notes: 'Heart stent placed in 2020. Strict low-sodium diet.',
        activeMedicineCount: 5,
        medicalRecordCount: 2,
      },
      {
        id: 'member-005',
        name: 'Priya Patel',
        relation: 'Sister',
        relationship: 'Sister',
        dateOfBirth: '2005-06-18',
        gender: 'Female',
        bloodGroup: 'A+',
        avatarInitials: 'PP',
        avatarColor: '#C9A882',
        allergies: ['Shellfish'],
        conditions: [],
        emergencyContact: '+91 98765 43210',
        emergencyContactName: 'Meena Patel (Mother)',
        activeMedicineCount: 0,
        medicalRecordCount: 0,
      },
    ],

    doctors: [
      {
        id: 'doctor-001',
        name: 'Dr. Sunil Mehta',
        specialty: 'Diabetologist',
        specialization: 'Diabetologist',
        hospital: 'Apollo Hospital',
        clinic: 'Apollo Diabetes & Endocrine Centre',
        phone: '+91 79 6670 1234',
        email: 'dr.mehta@apollo.com',
        address: 'Bhat, Gandhinagar - Ahmedabad',
        familyMemberIds: ['member-002', 'member-004'],
        notes: 'Monitors Meena & Hirabhai for diabetes and metabolic health.',
      },
      {
        id: 'doctor-002',
        name: 'Dr. Anita Rao',
        specialty: 'Cardiologist',
        specialization: 'Cardiologist',
        hospital: 'Sterling Hospital',
        clinic: 'Sterling Heart Institute',
        phone: '+91 79 4001 5678',
        email: 'anita.rao@sterling.in',
        address: 'Memnagar, Ahmedabad',
        familyMemberIds: ['member-004'],
        notes: 'Hirabhai’s cardiologist for post-stent cardiac management.',
      },
      {
        id: 'doctor-003',
        name: 'Dr. Kavita Shah',
        specialty: 'General Physician',
        specialization: 'General Physician',
        hospital: 'Shrey Hospital',
        clinic: 'Shah Family Care Clinic',
        phone: '+91 79 2755 9900',
        email: 'kavita.shah@shreyhealth.org',
        address: 'Navrangpura, Ahmedabad',
        familyMemberIds: ['member-001', 'member-002', 'member-003', 'member-005'],
        notes: 'Family doctor for annual wellness exams and preventive vaccinations.',
      },
      {
        id: 'doctor-004',
        name: 'Dr. Ramesh Joshi',
        specialty: 'Endocrinologist',
        specialization: 'Endocrinologist',
        hospital: 'Apollo Hospital',
        clinic: 'Thyroid & Hormone Care',
        phone: '+91 79 6670 4321',
        email: 'r.joshi@apollo.com',
        address: 'Bhat, Gandhinagar - Ahmedabad',
        familyMemberIds: ['member-003'],
        notes: 'Reviews Rajesh’s TSH and thyroid dosing twice a year.',
      },
    ],

    medicines: [
      // Meena Patel (Mom)
      {
        id: 'med-001',
        familyMemberId: 'member-002',
        name: 'Metformin',
        dosage: '500 mg',
        frequency: 2,
        times: ['08:00', '20:00'],
        timing: 'After meal',
        beforeAfterFood: 'after_food',
        startDate: addDays(today, -60),
        isActive: true,
        purpose: 'Type 2 Diabetes',
        doctorId: 'doctor-001',
        notes: 'Take with a full glass of water after breakfast and dinner.',
      },
      {
        id: 'med-002',
        familyMemberId: 'member-002',
        name: 'Amlodipine',
        dosage: '5 mg',
        frequency: 1,
        times: ['09:00'],
        timing: 'Before meal',
        beforeAfterFood: 'before_food',
        startDate: addDays(today, -30),
        isActive: true,
        purpose: 'Hypertension',
        doctorId: 'doctor-001',
        notes: 'Morning blood pressure medication.',
      },
      {
        id: 'med-003',
        familyMemberId: 'member-002',
        name: 'Vitamin D3',
        dosage: '60000 IU',
        frequency: 1,
        times: ['10:00'],
        timing: 'After meal',
        beforeAfterFood: 'after_food',
        startDate: addDays(today, -14),
        endDate: addDays(today, 45),
        isActive: true,
        purpose: 'Bone health & Vitamin D deficiency',
        doctorId: 'doctor-003',
        notes: 'Weekly capsule on Sunday mornings.',
      },

      // Rajesh Patel (Dad)
      {
        id: 'med-004',
        familyMemberId: 'member-003',
        name: 'Levothyroxine',
        dosage: '50 mcg',
        frequency: 1,
        times: ['07:00'],
        timing: 'Before meal',
        beforeAfterFood: 'before_food',
        startDate: addDays(today, -90),
        isActive: true,
        purpose: 'Hypothyroidism',
        doctorId: 'doctor-004',
        notes: 'Take on empty stomach 30 mins before morning chai.',
      },
      {
        id: 'med-005',
        familyMemberId: 'member-003',
        name: 'Diclofenac Gel',
        dosage: '1% topical',
        frequency: 2,
        times: ['08:30', '20:30'],
        timing: 'Anytime',
        beforeAfterFood: 'any',
        startDate: addDays(today, -10),
        isActive: true,
        purpose: 'Arthritis pain relief',
        doctorId: 'doctor-003',
        notes: 'Apply gently over knee joints.',
      },

      // Hirabhai Patel (Grandfather)
      {
        id: 'med-006',
        familyMemberId: 'member-004',
        name: 'Metformin',
        dosage: '1000 mg',
        frequency: 2,
        times: ['08:00', '20:00'],
        timing: 'After meal',
        beforeAfterFood: 'after_food',
        startDate: addDays(today, -120),
        isActive: true,
        purpose: 'Type 2 Diabetes',
        doctorId: 'doctor-001',
        notes: 'Maintain steady timing after food.',
      },
      {
        id: 'med-007',
        familyMemberId: 'member-004',
        name: 'Rosuvastatin',
        dosage: '10 mg',
        frequency: 1,
        times: ['21:00'],
        timing: 'After meal',
        beforeAfterFood: 'after_food',
        startDate: addDays(today, -120),
        isActive: true,
        purpose: 'Cholesterol & CAD management',
        doctorId: 'doctor-002',
        notes: 'Nightly dose before bedtime.',
      },
      {
        id: 'med-008',
        familyMemberId: 'member-004',
        name: 'Carvedilol',
        dosage: '6.25 mg',
        frequency: 2,
        times: ['08:00', '20:00'],
        timing: 'With meal',
        beforeAfterFood: 'with_food',
        startDate: addDays(today, -120),
        isActive: true,
        purpose: 'Heart rate & BP support',
        doctorId: 'doctor-002',
      },
      {
        id: 'med-009',
        familyMemberId: 'member-004',
        name: 'Ramipril',
        dosage: '5 mg',
        frequency: 1,
        times: ['09:00'],
        timing: 'Before meal',
        beforeAfterFood: 'before_food',
        startDate: addDays(today, -120),
        isActive: true,
        purpose: 'Cardiovascular protection',
        doctorId: 'doctor-002',
      },
      {
        id: 'med-010',
        familyMemberId: 'member-004',
        name: 'Pantoprazole',
        dosage: '40 mg',
        frequency: 1,
        times: ['07:00'],
        timing: 'Before meal',
        beforeAfterFood: 'before_food',
        startDate: addDays(today, -60),
        isActive: true,
        purpose: 'Gastric protection',
        doctorId: 'doctor-003',
      },

      // Tirth Patel (Self)
      {
        id: 'med-011',
        familyMemberId: 'member-001',
        name: 'Cetirizine',
        dosage: '10 mg',
        frequency: 1,
        times: ['21:00'],
        timing: 'After meal',
        beforeAfterFood: 'after_food',
        startDate: addDays(today, -14),
        endDate: addDays(today, 14),
        isActive: true,
        purpose: 'Seasonal allergy relief',
        doctorId: 'doctor-003',
        notes: 'May cause mild drowsiness.',
      },
    ],

    doses: [
      { id: 'dl-1', medicineId: 'med-001', date: addDays(today, -1), time: '08:00', status: 'taken', recordedAt: '' },
      { id: 'dl-2', medicineId: 'med-001', date: addDays(today, -1), time: '20:00', status: 'taken', recordedAt: '' },
      { id: 'dl-3', medicineId: 'med-002', date: addDays(today, -1), time: '09:00', status: 'taken', recordedAt: '' },
      { id: 'dl-4', medicineId: 'med-004', date: addDays(today, -1), time: '07:00', status: 'taken', recordedAt: '' },
      { id: 'dl-5', medicineId: 'med-001', date: today, time: '08:00', status: 'taken', recordedAt: '' },
      { id: 'dl-6', medicineId: 'med-002', date: today, time: '09:00', status: 'taken', recordedAt: '' },
      { id: 'dl-7', medicineId: 'med-004', date: today, time: '07:00', status: 'taken', recordedAt: '' },
      { id: 'dl-8', medicineId: 'med-006', date: today, time: '08:00', status: 'taken', recordedAt: '' },
    ],

    vaccinations: [
      {
        id: 'vacc-001',
        familyMemberId: 'member-001',
        name: 'COVID-19 (Covishield) - Dose 2',
        vaccine: 'COVID-19 (Covishield)',
        dose: 'Dose 2',
        dateAdministered: '2021-07-20',
        date: '2021-07-20',
        hospital: 'AMC Vaccination Centre',
        notes: 'Completed full primary regimen.',
      },
      {
        id: 'vacc-002',
        familyMemberId: 'member-001',
        name: 'COVID-19 Booster',
        vaccine: 'COVID-19 Booster',
        dose: 'Precaution Dose',
        dateAdministered: '2022-04-10',
        date: '2022-04-10',
        hospital: 'Shrey Hospital',
      },
      {
        id: 'vacc-003',
        familyMemberId: 'member-002',
        name: 'Influenza (Flu) Shot',
        vaccine: 'Influenza (Flu)',
        dose: 'Annual',
        dateAdministered: addDays(today, -300),
        date: addDays(today, -300),
        nextDueDate: addDays(today, 65),
        hospital: 'Shrey Hospital',
        notes: 'Annual booster recommended before monsoon season.',
      },
      {
        id: 'vacc-004',
        familyMemberId: 'member-004',
        name: 'Pneumococcal (PCV23)',
        vaccine: 'Pneumococcal (PCV23)',
        dose: 'Booster',
        dateAdministered: addDays(today, -400),
        date: addDays(today, -400),
        nextDueDate: addDays(today, 180),
        hospital: 'Apollo Hospital',
        notes: 'Recommended for cardiac and diabetic seniors.',
      },
      {
        id: 'vacc-005',
        familyMemberId: 'member-003',
        name: 'Tetanus (Td Booster)',
        vaccine: 'Tetanus Toxoid',
        dose: 'Booster',
        dateAdministered: '',
        nextDueDate: addDays(today, 14),
        hospital: 'Apollo Hospital',
        notes: 'Routine 10-year booster due soon.',
      },
    ],

    emergency: [
      {
        familyMemberId: 'member-002',
        bloodGroup: 'A+',
        allergies: ['Sulfa drugs', 'Dust mites'],
        conditions: ['Type 2 Diabetes', 'Hypertension'],
        emergencyContactName: 'Rajesh Patel (Husband)',
        emergencyContactPhone: '+91 98765 43210',
        primaryDoctorId: 'doctor-001',
        notes: 'Carries emergency glucose tablets in purse.',
      },
      {
        familyMemberId: 'member-004',
        bloodGroup: 'O+',
        allergies: ['Aspirin'],
        conditions: ['Type 2 Diabetes', 'Coronary Artery Disease', 'Cataracts'],
        emergencyContactName: 'Rajesh Patel (Son)',
        emergencyContactPhone: '+91 98765 43210',
        primaryDoctorId: 'doctor-002',
        notes: 'Heart stent in LAD (2020). Severe allergy to Aspirin/NSAIDs.',
      },
      {
        familyMemberId: 'member-003',
        bloodGroup: 'B+',
        allergies: [],
        conditions: ['Hypothyroidism', 'Mild Arthritis'],
        emergencyContactName: 'Meena Patel (Wife)',
        emergencyContactPhone: '+91 98765 43210',
        primaryDoctorId: 'doctor-004',
        notes: 'Daily morning Levothyroxine.',
      },
      {
        familyMemberId: 'member-001',
        bloodGroup: 'B+',
        allergies: ['Penicillin'],
        conditions: [],
        emergencyContactName: 'Rajesh Patel (Father)',
        emergencyContactPhone: '+91 98765 43210',
        primaryDoctorId: 'doctor-003',
        notes: 'Penicillin allergy causes anaphylactoid hives and facial edema.',
      },
      {
        familyMemberId: 'member-005',
        bloodGroup: 'A+',
        allergies: ['Shellfish'],
        conditions: [],
        emergencyContactName: 'Meena Patel (Mother)',
        emergencyContactPhone: '+91 98765 43210',
        primaryDoctorId: 'doctor-003',
        notes: 'Carries oral antihistamine in college bag.',
      },
    ],

    records: [
      {
        id: 'record-001',
        familyMemberId: 'member-002',
        title: 'HbA1c & Fasting Blood Sugar',
        type: 'Lab Report',
        kind: 'report',
        date: addDays(today, -15),
        doctorId: 'doctor-001',
        doctorName: 'Dr. Sunil Mehta',
        hospital: 'Apollo Hospital',
        summary: 'HbA1c at 7.2% — within diabetic target range. Fasting glucose at 128 mg/dL. Continue current Metformin 500mg dose.',
        tags: ['Diabetes', 'Blood Work', 'Routine'],
        notes: 'Review with Dr. Sunil Mehta in 3 months.',
      },
      {
        id: 'record-002',
        familyMemberId: 'member-004',
        title: 'Cardiac Stress Echo & ECG',
        type: 'Imaging',
        kind: 'report',
        date: addDays(today, -25),
        doctorId: 'doctor-002',
        doctorName: 'Dr. Anita Rao',
        hospital: 'Sterling Hospital',
        summary: 'Normal resting ECG. Mild inducible wall motion abnormality at peak workload. Stable compared to last year.',
        tags: ['Cardiology', 'ECG', 'Stress Test'],
        notes: 'LVEF estimated at 55%. Continue Carvedilol & Rosuvastatin.',
      },
      {
        id: 'record-003',
        familyMemberId: 'member-001',
        title: 'Annual Health Checkup & CBC',
        type: 'Consultation',
        kind: 'report',
        date: addDays(today, -30),
        doctorId: 'doctor-003',
        doctorName: 'Dr. Kavita Shah',
        hospital: 'Shrey Hospital',
        summary: 'All vitals normal. Hemoglobin 15.2 g/dL. Recommended increased hydration and exercise.',
        tags: ['Annual Checkup', 'Vitals', 'Routine'],
        notes: 'Blood pressure 118/76 mmHg. Heart rate 72 bpm.',
      },
      {
        id: 'record-004',
        familyMemberId: 'member-003',
        title: 'Thyroid Function Panel (TSH, FT4)',
        type: 'Lab Report',
        kind: 'report',
        date: addDays(today, -20),
        doctorId: 'doctor-004',
        doctorName: 'Dr. Ramesh Joshi',
        hospital: 'Apollo Hospital',
        summary: 'TSH slightly elevated at 5.1 uIU/mL. Free T4 normal. Levothyroxine maintained at 50 mcg.',
        tags: ['Thyroid', 'Endocrinology'],
        notes: 'Recheck TSH in 6 months.',
      },
      {
        id: 'record-005',
        familyMemberId: 'member-002',
        title: 'Chest X-Ray (PA View)',
        type: 'Imaging',
        kind: 'report',
        date: addDays(today, -45),
        doctorId: 'doctor-003',
        doctorName: 'Dr. Kavita Shah',
        hospital: 'Shrey Hospital',
        summary: 'Clear lung fields bilaterally. Normal cardiac silhouette. No active pulmonary pathology.',
        tags: ['Radiology', 'Lungs'],
        notes: 'Routine pre-procedure clearance.',
      },
      {
        id: 'record-006',
        familyMemberId: 'member-004',
        title: 'Cataract Progression Evaluation',
        type: 'Consultation',
        kind: 'report',
        date: addDays(today, -40),
        doctorId: 'doctor-003',
        doctorName: 'Dr. Preet Bhatia',
        hospital: 'Centre for Sight, Ahmedabad',
        summary: 'Nuclear sclerosis grade II in left eye. Vision corrected to 6/9 with lenses. Review in 6 months.',
        tags: ['Eye', 'Ophthalmology'],
        notes: 'Surgical intervention recommended if glare interferes with daily reading.',
      },
    ],

    appointments: [
      {
        id: 'apt-001',
        familyMemberId: 'member-002',
        doctorId: 'doctor-001',
        doctorName: 'Dr. Sunil Mehta',
        specialty: 'Diabetologist',
        hospital: 'Apollo Hospital',
        dateTime: `${addDays(today, 5)}T10:30:00`,
        status: 'Upcoming',
        notes: 'Quarterly HbA1c review and glucose trend check.',
      },
      {
        id: 'apt-002',
        familyMemberId: 'member-004',
        doctorId: 'doctor-002',
        doctorName: 'Dr. Anita Rao',
        specialty: 'Cardiologist',
        hospital: 'Sterling Hospital',
        dateTime: `${addDays(today, 8)}T09:00:00`,
        status: 'Upcoming',
        notes: 'Routine post-stent cardiac evaluation and ECG check.',
      },
      {
        id: 'apt-003',
        familyMemberId: 'member-003',
        doctorId: 'doctor-004',
        doctorName: 'Dr. Ramesh Joshi',
        specialty: 'Endocrinologist',
        hospital: 'Apollo Hospital',
        dateTime: `${addDays(today, 12)}T11:00:00`,
        status: 'Upcoming',
        notes: 'Thyroid dose review with fresh TSH results.',
      },
      {
        id: 'apt-004',
        familyMemberId: 'member-001',
        doctorId: 'doctor-003',
        doctorName: 'Dr. Kavita Shah',
        specialty: 'General Physician',
        hospital: 'Shrey Hospital',
        dateTime: `${addDays(today, 20)}T14:00:00`,
        status: 'Upcoming',
        notes: 'Annual follow-up checkup.',
      },
    ],
  };
}
